name: Main

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - rubyver: 3.1.2
            gemfile: gemfiles/rails70.gemfile

    env:
      RAILS_ENV: test

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          ruby-version: ${{ matrix.rubyver }}
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true

      - name: Run tests
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
        run: |
          bundle exec rake test
