name: Main

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - gemfile: gemfiles/rails50.gemfile
            rubyver: 2.4.6
          - gemfile: gemfiles/rails51.gemfile
            rubyver: 2.4.6
          - gemfile: gemfiles/rails52.gemfile
            rubyver: 2.4.6
          - gemfile: gemfiles/rails60.gemfile
            rubyver: 2.6.8
          - gemfile: gemfiles/rails61.gemfile
            rubyver: 2.7.4
          - gemfile: gemfiles/rails70.gemfile
            rubyver: 3.1.2

    env:
      RAILS_ENV: test
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          ruby-version: ${{ matrix.rubyver }}
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true

      - name: Run tests
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
        run: |
          bundle exec rake test
